### ISSUE TITLE
Only first block of MetaData is reported

### ISSUE THREAD

**Issue by sebsto** [saschpe/android-exoplayer2-ext-icy#11]
Since the upgrade to ExoPlayer 2.10, only the first block of meta data from the stream is reported to listeners.  Subsequent blocks are ignored.

You can test with the steam https://audio.maxi80.com 

The culprit is this line of code https://github.com/saschpe/android-exoplayer2-ext-icy/commit/537a1b6d176fb0ad7c7ff39288588bb014100255#diff-039576ecd822048f37ed9e534e84b411R171 added in this commit https://github.com/saschpe/android-exoplayer2-ext-icy/commit/537a1b6d176fb0ad7c7ff39288588bb014100255

The `metaDataIntervalInBytes` is reset to zero after the first block is read.  This is incorrect as this value is constant during the entire duration of the stream.  

Unfortunately, fixing this is more than just deleting this line of code.  I am investigating and will eventually send a PR when I will find a solution.

**Comment by cjamcu** [comment]
@sebsto Some fix for this problem ?

**Comment by sebsto** [comment]
@cjamcu hello Javier. IcyMetaData are now natively supported by ExoPlayer so I switched my project to ExoPlayer. 
My project is here https://github.com/sebsto/maxi-80-android-exoplayer2

**Comment by saschpe** [comment]
Indeed. The code is now part of ExoPlayer and this library therefore deprecated.
