### ISSUE TITLE
Failed to resolve: saschpe.android:exoplayer2-ext-icy:2.1.0

### ISSUE THREAD

**Issue by vinsensiusarko** [saschpe/android-exoplayer2-ext-icy#15]
when i check at url "https://repo1.maven.org/maven2/saschpe/android/exoplayer2-ext-icy/2.1.0/exoplayer2-ext-icy-2.1.0.pom" is missing

**Comment by saschpe** [comment]
Please be aware that this extension is now part of AndroidX Media directly. See https://github.com/androidx/media/blob/c35a9d62baec57118ea898e271ac66819399649b/libraries/extractor/src/main/java/androidx/media3/extractor/metadata/icy/IcyInfo.java

MimeType: APPLICATION_ICY
