### ISSUE TITLE
Gradle Sync Issue

### ISSUE THREAD

**Issue by 7FM** [saschpe/android-exoplayer2-ext-icy#8]
When building I get the following warning:
WARNING: API 'variant.getJavaCompile()' is obsolete and has been replaced with 'variant.getJavaCompileProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getJavaCompile(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
Affected Modules: exoplayer2-ext-icy

Used gradle Version: 4.10.1
Android plugin Version: 3.3.0

**Comment by sebsto** [comment]
+1

**Comment by saschpe** [comment]
Not something I have under control. It's the Android Gradle plugin

**Comment by sebsto** [comment]
Actually, my understanding is that a construct used in the Gradle build script will be deprecated by the end of the year.  Gradle is not under your control, but the build script is :-)  Can you have a look and report back ?  I tried to fix this myself but I am not Gradle expert and could not do it.
